### ISSUE TITLE
The projects list are squeezed in one row 

### ISSUE THREAD

**Issue by xiaodongliang** [petrbroz/bim360-issue-editor#1]
When there are may projects in one hubs, they are squeezed in one row
<img width="791" alt="Screen Shot 2019-11-07 at 7 29 49 PM" src="https://user-images.githubusercontent.com/5087461/68386033-21ae1380-0196-11ea-8335-e0b17a5ed958.png">

**Comment by petrbroz** [comment]
Fixed in https://github.com/petrbroz/bim360-issue-editor/commit/90b653f32c633f0810ddf040ee0d6453e77b9e03.
