### ISSUE TITLE
the popup dialog of attachment and comments cannot disappear until refreshing the page

### ISSUE THREAD

**Issue by xiaodongliang** [petrbroz/bim360-issue-editor#3]
The dialog is docked on top of the screen, even the the mouse focus swifts. maybe adding a close button? 
<img width="449" alt="Screen Shot 2019-11-07 at 7 32 41 PM" src="https://user-images.githubusercontent.com/5087461/68386269-a4cf6980-0196-11ea-8f3d-a496a60be43f.png">

**Comment by petrbroz** [comment]
With the default behavior, the popovers can be closed by clicking on the button again. I do agree that this isn't very intuitive, though. Let me add an explicit close button there as well.
