### ISSUE TITLE
requested ressource does not exist upon trying to login

### ISSUE THREAD

**Issue by jmcouffin** [petrbroz/bim360-issue-editor#32]
trying to login in the demo after provisionning in bim360 admin panel, I get this error:

{"developerMessage":"The requested resource does not exist.","errorCode":"","moreInfo":"https://forge.autodesk.com/en/docs/oauth/v2/developers_guide/error_handling/"}

**Comment by petrbroz** [comment]
Thanks for the heads up @jmcouffin. Please note that this is an old code sample (I will mark it as deprecated) which has now been moved to https://github.com/autodesk-platform-services/bim360-issue-editor. It looks like the migrated code sample is also having some issues, so I'm going to contact the new owner to look into it.

**Comment by jmcouffin** [comment]
thanks for the followup
