### ISSUE TITLE
failed to download attachment

### ISSUE THREAD

**Issue by xiaodongliang** [petrbroz/bim360-issue-editor#4]
The error is { "developerMessage":"Token is not provided in the request.", "moreInfo": "https://forge.autodesk.com/en/docs/oauth/v2/developers_guide/error_handling/", "errorCode": "AUTH-010"}

**Comment by petrbroz** [comment]
Fixed in https://github.com/petrbroz/bim360-issue-editor/commit/5db861a90ae5927fec1fb49098bf0de0c3f2770a.
