### ISSUE TITLE
HTML encode for description

### ISSUE THREAD

**Issue by augustogoncalves** [petrbroz/bim360-issue-editor#8]
I have some links on my issues ([here is how it's created](https://github.com/Autodesk-Forge/forge-checkmodels-createissues-revit/blob/master/web/Controllers/DesignAutomationController.cs#L94)), and it breaks the app UI, maybe just missing an HTML Encode call

![image](https://user-images.githubusercontent.com/4291593/82094966-f101e600-96b2-11ea-9161-9d010d631e66.png)

**Comment by petrbroz** [comment]
Interesting hack :) Yes, the UI is generated on the client and there was no HTML encoding. Added one just now: https://github.com/petrbroz/bim360-issue-editor/commit/c169f6fe18c08983b477360e484c054e645ffb80. Thanks for the heads up!
